language: java
jdk:
 - openjdk8
jobs:
 include:
 - stage: Artikel
   script: cd Artikel && ./gradlew build
 - stage: Benutzer
   script: cd Benutzer && ./gradlew build
 - stage: Lending
   script: cd Lending && ./gradlew build
notifications:
 - email: false
