version: "3.1"
services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=person_database
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    # Einkommentieren zum Persistieren der Daten
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  initializer:
    build:
      context: ./DatabaseInitializer
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
