version: "3.5"
services:
  rhinoshareapp:
    build:
      context: ./rhinoshareapp
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    command: ["./wait-for-it.sh", "database:3306", "propay:8888", "--", "java", "-jar", "app.jar"]
    depends_on:
      - database
      - propay
    networks:
      - web


  propay:
    image: propra/propay
    ports:
      - "8888:8888"
    # Optional
    volumes:
      - ./data:/code/data
    depends_on:
      - database
    networks:
      - web

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: springboot_mariadb
    networks:
      - web
    volumes:
      - ./datadir:/var/lib/mysql
volumes:
  datadir:
networks:
  web:
    name: web
