version: "3.5"
services:

  rhinoshareapp:
    build:
      context: ./rhinoshareapp
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    command: ["./wait-for-it.sh", "database:5432", "propay:8888", "--", "java", "-jar", "app.jar"]
    depends_on:
      - database
      - propay


  propay:
    image: propra/propay
    ports:
      - "8888:8888"
    # Optional
    volumes:
      - ./data:/code/data
    depends_on:
      - database

  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=rhinoshare_default
      - POSTGRES_DB=database
      - POSTGRES_USER=rhinoshare
    volumes:
      - ./data:/var/lib/postgresql/data
